eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9031
spring:
  application:
    name: eureka-client
  datasource:
    url: jdbc:mysql://localhost:3306/wangchun
    username: root
    password: 1q2w3e4r
    driverClassName: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
  jpa:
    database: MYSQL
    # Show or not log for each sql query
    show-sql: true
    # Hibernate ddl auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      # Naming strategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      # stripped before adding them to the entity manager)
    properties:
      hibernate:
        # stripped before adding them to the entity manager)
        dialect: org.hibernate.dialect.MySQL5Dialect
        # 解决SessionFactory找不到
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext